# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  lifemanagerblazorserverui:
    image: lifemanagerblazorserverui
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 25029
      - 44325
      - 5000
      - 5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:25029
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
